# swagger configuration file

# values in the swagger hash are system configuration for swagger-node
swagger:

  fittingsDirs: [ api/fittings ]
  defaultPipe: null
  swaggerControllerPipe: swagger_controllers  # defines the standard processing pipe for controllers

  # values defined in the bagpipes key are the bagpipes pipes and fittings definitions
  # (see https://github.com/apigee-127/bagpipes)
  bagpipes:

    _router:
      name: swagger_router
      mockMode: false
      mockControllersDirs: [ api/mocks ]
      controllersDirs: [ api/controllers ]

    _swagger_validate:
      name: swagger_validator
      validateResponse: true

    _cors:
      name: cors
      origin:
        - http[s]{0,1}:\/\/(localhost:[0-9]{4,}|.+\.mydomain\.com)$
      methods:
        - "GET"
        - "PUT"
        - "POST"
        - "OPTIONS"
        - "PUT"
        - "PATCH"
        - "DELETE"
      allowedHeaders:
        - "X-Requested-With"
        - "X-HTTP-Method-Override"
        - "Content-Type"
        - "Accept"

    # pipe for all swagger-node controllers
    swagger_controllers:
      #Swagger-express-mw/node_modules/swagger-node-runner/fittings has the following files. To override the behavior, create these files under api/fittings folder.
      - onError: json_error_handler
      - _cors
      - swagger_security
      - _swagger_validate
      - express_compatibility
      - _router

    # pipe to serve swagger (endpoint is in swagger.yaml)
    swagger_raw:
      name: swagger_raw

# any other values in this file are just loaded into the config for application access...
